### ISSUE TITLE
when build 'ostro-image-swupd' , the python lack Queue module?

### ISSUE THREAD

**Issue by wenij** [ostroproject/ostro-os#87]
When build with 'ostro-image-swupd', this python module don't include Queue.
I think it should be essential for Python package.
Do you know what package should be include ?

**Comment by gvancuts** [comment]
Hi @wenij , during my discussion with engineering, it appeared that the non -dev images are really images which contain only the essential packages to boot a system (and not much else). They don't, as an example, include things like iotivity and other packages you may want. The problem you are reporting _may_ be the result of the same policy applied when the content of the core image was defined.

@pohly : any further comment?

**Comment by pohly** [comment]
@gvancuts your explanation is correct. Queue.py gets packaged as python-threading, and that only gets installed in the -dev images as part of the full Python runtime.

The more minimal images happen to have Python, probably because something depends on it, but not the python-threading package. Whether the minimal images have Python or how much of it can't be relied upon, because it is basically an "implementation detail" of Ostro.

**Comment by pohly** [comment]
I believe the question was answered, so I'm closing the issue.
